version: 2
updates:
  # Enable version updates for Python
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "@Singosgu"
    assignees:
      - "@Singosgu"
    commit-message:
      prefix: "pip"
      prefix-development: "pip-dev"
      include: "scope"
    ignore:
      # Ignore major version updates for critical dependencies
      - dependency-name: "django"
        update-types: ["version-update:semver-major"]
      - dependency-name: "vue"
        update-types: ["version-update:semver-major"]

  # Enable version updates for npm/yarn
  - package-ecosystem: "npm"
    directory: "bomiot/templates"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "@Singosgu"
    assignees:
      - "@Singosgu"
    ignore:
      # Ignore major version updates for critical dependencies
      - dependency-name: "vue"
        update-types: ["version-update:semver-major"]
      - dependency-name: "quasar"
        update-types: ["version-update:semver-major"]

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "@Singosgu"
    assignees:
      - "@Singosgu"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "@Singosgu"
    assignees:
      - "@Singosgu" 