# These are supported funding model platforms

github: [Singosgu] # Bomiot project maintainer
patreon: # Add if you have Patreon
open_collective: # Add if you have Open Collective
ko_fi: # Add if you have Ko-fi
tidelift: # Add if you have Tidelift
community_bridge: # Add if you have Community Bridge
liberapay: # Add if you have Liberapay
issuehunt: # Add if you have IssueHunt
otechie: # Add if you have Otechie
custom: https://github.com/Bomiot/Bomiot # Bomiot GitHub repository 