# GitHub Labels Configuration
# This file defines the labels used in the Bomiot repository

labels:
  # Bug labels
  - name: "bug"
    color: "d73a4a"
    description: "Something isn't working"
  - name: "bugfix"
    color: "d73a4a"
    description: "Bug fix"
  - name: "regression"
    color: "d73a4a"
    description: "Regression from previous version"

  # Feature labels
  - name: "enhancement"
    color: "a2eeef"
    description: "New feature or request"
  - name: "feature"
    color: "a2eeef"
    description: "New feature"
  - name: "good first issue"
    color: "7057ff"
    description: "Good for newcomers"

  # Component labels
  - name: "backend"
    color: "0366d6"
    description: "Django/Python backend changes"
  - name: "frontend"
    color: "ffa500"
    description: "Vue.js/Quasar frontend changes"
  - name: "cli"
    color: "00ff00"
    description: "Command line interface changes"
  - name: "plugin"
    color: "8b5cf6"
    description: "Plugin system changes"
  - name: "django"
    color: "092e20"
    description: "Django framework changes"
  - name: "vue"
    color: "42b883"
    description: "Vue.js changes"
  - name: "quasar"
    color: "1976d2"
    description: "Quasar framework changes"

  # Priority labels
  - name: "priority: high"
    color: "ff0000"
    description: "High priority"
  - name: "priority: medium"
    color: "ffa500"
    description: "Medium priority"
  - name: "priority: low"
    color: "00ff00"
    description: "Low priority"

  # Status labels
  - name: "status: blocked"
    color: "ff0000"
    description: "Blocked by another issue"
  - name: "status: in progress"
    color: "ffa500"
    description: "Work in progress"
  - name: "status: ready for review"
    color: "00ff00"
    description: "Ready for review"
  - name: "status: needs triage"
    color: "ffa500"
    description: "Needs triage"

  # Type labels
  - name: "documentation"
    color: "0075ca"
    description: "Improvements or additions to documentation"
  - name: "docs"
    color: "0075ca"
    description: "Documentation changes"
  - name: "performance"
    color: "ffa500"
    description: "Performance improvements"
  - name: "security"
    color: "ff0000"
    description: "Security related"
  - name: "testing"
    color: "00ff00"
    description: "Testing related"

  # Maintenance labels
  - name: "chore"
    color: "fef2c0"
    description: "Maintenance tasks"
  - name: "dependencies"
    color: "0366d6"
    description: "Pull requests that update a dependency file"
  - name: "refactor"
    color: "fef2c0"
    description: "Code refactoring"

  # Special labels
  - name: "breaking change"
    color: "ff0000"
    description: "Breaking change"
  - name: "duplicate"
    color: "cfd3d7"
    description: "This issue or pull request already exists"
  - name: "help wanted"
    color: "008672"
    description: "Extra attention is needed"
  - name: "invalid"
    color: "e4e669"
    description: "Something is wrong"
  - name: "question"
    color: "d876e3"
    description: "Further information is requested"
  - name: "wontfix"
    color: "ffffff"
    description: "This will not be worked on"

  # Bomiot specific labels
  - name: "i18n"
    color: "1f2937"
    description: "Internationalization and localization"
  - name: "permission"
    color: "dc2626"
    description: "Permission and authentication system"
  - name: "task-management"
    color: "059669"
    description: "Task scheduling and management"
  - name: "monitoring"
    color: "7c3aed"
    description: "System monitoring and health checks"
  - name: "deployment"
    color: "ea580c"
    description: "Deployment and DevOps" 