name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'dependencies'
  - title: '🔧 Backend'
    labels:
      - 'backend'
      - 'django'
  - title: '🎨 Frontend'
    labels:
      - 'frontend'
      - 'vue'
      - 'quasar'
  - title: '⚡ CLI'
    labels:
      - 'cli'
  - title: '🔌 Plugins'
    labels:
      - 'plugin'
  - title: '📚 Documentation'
    labels:
      - 'documentation'
      - 'docs'
template: |
  ## 🚀 Bomiot v$RESOLVED_VERSION

  $CHANGES

  ## 📦 Installation

  ```bash
  pip install bomiot==$RESOLVED_VERSION
  ```

  ## 🔧 Quick Start

  ```bash
  # Initialize Bomiot workspace
  bomiot init

  # Create a new project
  bomiot project my-project

  # Start the server
  bomiot run
  ```

  ## 🆕 What's New

  $CHANGES

  ## 🔧 Backend Changes

  $BACKEND_CHANGES

  ## 🎨 Frontend Changes

  $FRONTEND_CHANGES

  ## ⚡ CLI Updates

  $CLI_CHANGES

  ## 🔌 Plugin System

  $PLUGIN_CHANGES

  ## 📚 Documentation

  $DOCUMENTATION_CHANGES

  ## 🐛 Bug Fixes

  $BUG_FIXES

  ## 🔒 Security

  $SECURITY_FIXES

  ## ⚡ Performance

  $PERFORMANCE_IMPROVEMENTS

  ## 🧪 Testing

  $TESTING_CHANGES

  ## 📦 Dependencies

  $DEPENDENCY_UPDATES

  ## 🔄 Migration Guide

  $MIGRATION_GUIDE

  ## 💥 Breaking Changes

  $BREAKING_CHANGES

  ## 👥 Contributors

  $CONTRIBUTORS

  ## 📖 Full Changelog

  $FULL_CHANGELOG

  ## 🎥 Video Tutorials

  Check out our [YouTube channel](https://www.youtube.com/channel/UCPW1wciGMIEh7CYOdLnsloA) for tutorials and guides!

  ## 🤝 Support

  - [GitHub Issues](https://github.com/Bomiot/Bomiot/issues)
  - [GitHub Discussions](https://github.com/Bomiot/Bomiot/discussions)
  - [Documentation](https://github.com/Bomiot/Bomiot/wiki) 