name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '✨ Features'
    labels:
      - '✨ enhancement'
      - '🌟 feature'
  - title: '🐞 Bug Fixes'
    labels:
      - '🐞 bug'
      - '🛠 bugfix'
      - '⏪ regression'
  - title: '📝 Documentation'
    labels:
      - '📝 documentation'
      - 'docs'
  - title: '🎨 Frontend'
    labels:
      - '🎨 frontend'
  - title: '🖥️ Backend'
    labels:
      - '🖥️ backend'
  - title: '🔌 Plugins'
    labels:
      - '🔌 plugin'
  - title: '🌐 Internationalization'
    labels:
      - '🌐 i18n'
  - title: '🔒 Permission & Security'
    labels:
      - '🔒 permission'
      - '🔐 security'
  - title: '🗂️ Task Management'
    labels:
      - '🗂️ task-management'
  - title: '📈 Monitoring'
    labels:
      - '📈 monitoring'
  - title: '🚀 Deployment/DevOps'
    labels:
      - '🚀 deployment'
  - title: '⚙️ Performance'
    labels:
      - '⚙️ performance'
  - title: '🧪 Testing'
    labels:
      - '🧪 testing'
  - title: '🧹 Maintenance'
    labels:
      - '🧹 chore'
      - '📦 dependencies'
      - '♻️ refactor'
  - title: '💥 Breaking Changes'
    labels:
      - '💥 breaking change'
  - title: '❓ Other'
    labels:
      - 'question'
      - 'help wanted'
      - 'duplicate'
      - 'invalid'
      - 'wontfix'
template: |
  ## 📦 Bomiot v$RESOLVED_VERSION

  $CHANGES

  ## 📦 Installation
  ```bash
  pip install bomiot==$RESOLVED_VERSION
  ```

  ## 🆕 What's New
  $CHANGES

  ## 👥 Contributors
  $CONTRIBUTORS

  ## 📖 Full Changelog
  $FULL_CHANGELOG

  ## 🎥 Video Tutorials
  - [YouTube Channel](https://www.youtube.com/channel/UCPW1wciGMIEh7CYOdLnsloA)

  ## 🤝 Support
  - [GitHub Issues](https://github.com/Bomiot/Bomiot/issues)
  - [GitHub Discussions](https://github.com/Bomiot/Bomiot/discussions) 