[login]
"Please Login Again"="Please Login Again"
"User is not active"="User is not active"
"User not exists"="User not exists"
"Please Login First"="Please Login First"
"User or Password error"="User or Password error"
"User Not Log In"="User Not Log In"
"Get Permission List"="Get Permission List"

[permission]
"Get User List"="Get User List"
"Create One User"="Create One User"
"Set Permission For User"="Set Permission For User"
"Change Password"="Change Password"
"Set Team For User"="Set Team For User"
"Set Department For User"="Set Department For User"
"Lock & Unlock User"="Lock & Unlock User"
"Delete One User"="Delete One User"
"Get Department List"="Get Department List"
"Create Department"="Create Department"
"Change Department"="Change Department"
"Delete Department"="Delete Department"
"Get Team List"="Get Team List"
"Create One Team"="Create One Team"
"Set Permission For Team"="Set Permission For Team"
"Change Team"="Change Team"
"Delete Team"="Delete Team"
"Get Goods List"="Get Goods List"
"Create Goods"="Create Goods"
"Update Goods"="Update Goods"
"Delete Goods"="Delete Goods"
"Get Bin List"="Get Bin List"
"Create Bin"="Create Bin"
"Update Bin"="Update Bin"
"Delete Bin"="Delete Bin"
"Get Stock List"="Get Stock List"
"Create Stock"="Create Stock"
"Update Stock"="Update Stock"
"Delete Stock"="Delete Stock"
"Get Capital List"="Get Capital List"
"Create Capital"="Create Capital"
"Update Capital"="Update Capital"
"Delete Capital"="Delete Capital"
"Get Supplier List"="Get Supplier List"
"Create Supplier"="Create Supplier"
"Update Supplier"="Update Supplier"
"Delete Supplier"="Delete Supplier"
"Get Customer List"="Get Customer List"
"Create Customer"="Create Customer"
"Update Customer"="Update Customer"
"Delete Customer"="Delete Customer"
"Get ASN List"="Get ASN List"
"Create ASN"="Create ASN"
"Update ASN"="Update ASN"
"Delete ASN"="Delete ASN"
"Get DN List"="Get DN List"
"Create DN"="Create DN"
"Update DN"="Update DN"
"Delete DN"="Delete DN"
"Get Purchase List"="Get Purchase List"
"Create Purchase"="Create Purchase"
"Update Purchase"="Update Purchase"
"Delete Purchase"="Delete Purchase"
"Get Bar List"="Get Bar List"
"Create Bar"="Create Bar"
"Update Bar"="Update Bar"
"Delete Bar"="Delete Bar"
"Get Fee List"="Get Fee List"
"Create Fee"="Create Fee"
"Update Fee"="Update Fee"
"Delete Fee"="Delete Fee"
"Get Driver List"="Get Driver List"
"Create Driver"="Create Driver"
"Update Driver"="Update Driver"
"Delete Driver"="Delete Driver"
"Get Example List"="Get Example List"
"Create Example"="Create Example"
"Update Example"="Update Example"
"Delete Example"="Delete Example"



[detail]
"User exists"="User exists"
"User not exists"="User not exists"
"User does not have permission to create user"="User does not have permission to create user"
"Can not change admin's permision"="Can not change admin's permision"
"Can not change your own permission"="Can not change your own permission"
"User does not have permission to set permission for user"="User does not have permission to set permission for user"
"User does not have permission to change password"="User does not have permission to change password"
"User can only change your own password"="User can only change your own password"
"Can not lock admin"="Can not lock admin"
"User does not have permission to lock user"="User does not have permission to lock user"
"User can not lock/unlock your own"="User can not lock/unlock your own"
"Can not delete admin"="Can not delete admin"
"User does not have permission to delete user"="User does not have permission to delete user"
"User can not delete your own"="User can not delete your own"
"File not exists"="File not exists"
"Can not share file which is not your own"="Can not share file which is not your own"
"Can not delete file which is not your own"="Can not delete file which is not your own"
"Department exists"="Department exists"
"Department not exists"="Department not exists"
"User does not have permission to create department"="User does not have permission to create department"
"User does not have permission to change department"="User does not have permission to change department"
"User does not have permission to delete department"="User does not have permission to delete department"
"Team exists"="Team exists"
"Team not exists"="Team not exists"
"User does not have permission to create team"="User does not have permission to create team"
"User does not have permission to change team"="User does not have permission to change team"
"User does not have permission to delete team"="User does not have permission to delete team"

[msg]
"Success Create User"="Success Create User"
"Success set team"="Success Set User Team"
"Success set department"="Success Set User Department"
"Success Change Password"="Success Change Password"
"Success lock User"="Success lock User"
"Success unlock User"="Success unlock User"
"Success delete User"="Success delete User"
"Success upload file"="Success upload file"
"Success share your file"="Success share your file"
"Success delete file"="Success delete file"
"Success create department"="Success create department"
"Success change department"="Success change department"
"Success delete department"="Success delete department"
"Success create team"="Success create team"
"Success change team"="Success change team"
"Success delete team"="Success delete team"
"Success Create"="Success Create"
"Success Update"="Success Update"
"Success Delete"="Success Delete"

[others]
"Success Login"="Success Login"
"Welcome Back Again"="Welcome Back Again"
"CPU Info"="CPU Info"
"CPU Usage"="CPU Usage"
"Memory Info"="Memory Info"
"Memory Usad"="Memory Usad"
"Memory Free"="Memory Free"
"Disk Info"="Disk Info"
"Disk Used"="Disk Usad"
"Disk Free"="Disk Free"
"Network Info"="Network Info"
"Bytes Sent"="Bytes Sent"
"Bytes Received"="Bytes Received"
"Success upload files"="Success upload files"
"File type not allowed"="File type not allowed"
"File size exceeds limit"="File size exceeds limit"