[login]
"Please Login Again"="请再次登入"
"User is not active"="用户被锁定，请联系管理员解锁"
"Please Login First"="请先登入"
"User not exists"="用户不存在"
"User or Password error"="用户或者密码错误"
"User Not Log In"="用户未登入"
"Get Permission List"="获取权限列表"

[permission]
"Get User List"="获取用户列表"
"Create One User"="创建一个用户"
"Change Password"="修改密码"
"Set Team For User"="为用户设置用户组"
"Set Department For User"="为用户设置部门"
"Lock & Unlock User"="锁定或解锁用户"
"Delete One User"="删除一个用户"
"Get Department List"="获取部门列表"
"Create Department"="创建部门"
"Change Department"="修改部门"
"Delete Department"="删除部门"
"Get Team List"="获取用户组列表"
"Create One Team"="创建一个用户组"
"Set Permission For Team"="为用户组设置权限"
"Change Team"="修改用户组"
"Delete Team"="删除用户组"
"Get Goods List"="获取商品清单"
"Create Goods"="创建商品"
"Update Goods"="修改商品"
"Delete Goods"="删除商品"
"Get Bin List"="获取库位清单"
"Create Bin"="创建库位"
"Update Bin"="修改库位"
"Delete Bin"="删除库位"
"Get Stock List"="获取库存清单"
"Create Stock"="创建库存"
"Update Stock"="修改库存"
"Delete Stock"="删除库存"
"Get Capital List"="获取固定资产清单"
"Create Capital"="创建固定资产"
"Update Capital"="修改固定资产"
"Delete Capital"="删除固定资产"
"Get Supplier List"="获取供应商清单"
"Create Supplier"="创建供应商"
"Update Supplier"="修改供应商"
"Delete Supplier"="删除供应商"
"Get Customer List"="获取客户清单"
"Create Customer"="创建客户"
"Update Customer"="修改客户"
"Delete Customer"="删除客户"
"Get ASN List"="获取到货通知书清单"
"Create ASN"="创建到货通知书"
"Update ASN"="修改到货通知书"
"Delete ASN"="删除到货通知书"
"Get DN List"="获取发货单明细"
"Create DN"="创建发货单"
"Update DN"="修改发货单"
"Delete DN"="删除发货单"
"Get Purchase List"="获取采购单明细"
"Create Purchase"="创建采购单"
"Update Purchase"="修改采购单"
"Delete Purchase"="删除采购单"
"Get Bar List"="获取条码清单"
"Create Bar"="创建条码"
"Update Bar"="修改条码"
"Delete Bar"="删除条码"
"Get Fee List"="获取费用清单"
"Create Fee"="创建费用"
"Update Fee"="修改费用"
"Delete Fee"="删除费用"
"Get Driver List"="获取司机清单"
"Create Driver"="创建司机"
"Update Driver"="修改司机"
"Delete Driver"="删除司机"
"Get Example List"="获取示例清单"
"Create Example"="创建示例"
"Update Example"="修改示例"
"Delete Example"="删除示例"

[detail]
"User exists"="用户已存在"
"User not exists"="用户不存在"
"User does not have permission to create user"="用户没有创建用户的权限"
"Can not change admin's permision"="不可以修改管理员的权限"
"Can not change your own permission"="不可以修改你自己的权限"
"User does not have permission to set permission for user"="你没有修改用户的权限功能"
"User does not have permission to change password"="你没有修改密码的权限"
"User can only change your own password"="你只能修改你自己的密码"
"Can not lock admin"="不可以锁定管理员"
"User does not have permission to lock user"="用户没有锁定用户权限"
"User can not lock/unlock your own"="你不可以锁定自己"
"Can not delete admin"="不可以删除管理员"
"User does not have permission to delete user"="用户没有删除用户权限"
"User can not delete your own"="你不可以删除你自己"
"File not exists"="文件不存在"
"Can not share file which is not your own"="你不能分享别人的文件"
"Can not delete file which is not your own"="你不能删除别人的文件"
"Department exists"="部门已存在"
"Department not exists"="部门不存在"
"User does not have permission to create department"="你没有创建部门的权限"
"User does not have permission to change department"="你没有修改部门的权限"
"User does not have permission to delete department"="你没有删除部门的权限"
"Team exists"="用户组已存在"
"Team not exists"="用户组不存在"
"User does not have permission to create team"="你没有创建用户组的权限"
"User does not have permission to change team"="你没有修改用户组的权限"
"User does not have permission to delete team"="你没有删除用户组的权限"

[msg]
"Success Create User"="成功创建用户"
"Success set team"="成功分配用户组"
"Success set department"="成功分配部门"
"Success Change Password"="成功修改密码"
"Success lock User"="成功锁定用户"
"Success unlock User"="成功解锁用户"
"Success delete User"="删除用户成功"
"Success upload file"="成功上传文件"
"Success share your file"="成功分享文件"
"Success delete file"="成功删除文件"
"Success create department"="成功创建部门"
"Success change department"="成功修改部门"
"Success delete department"="删除部门成功"
"Success create team"="成功创建用户组"
"Success change team"="成功修改用户组"
"Success delete team"="删除部门用户组"
"Success Create"="成功创建"
"Success Update"="修改成功"
"Success Delete"="删除成功"

[others]
"Success Login"="登入成功"
"Welcome Back Again"="欢迎再次回来"
"CPU Info"="CPU监控信息"
"CPU Usage"="CPU使用率"
"Memory Info"="内存监控信息"
"Memory Usad"="内存已使用"
"Memory Free"="内存空闲"
"Disk Info"="硬盘监控信息"
"Disk Used"="硬盘已使用"
"Disk Free"="硬盘空余"
"Network Info"="网络监控信息"
"Bytes Sent"="上传数据量"
"Bytes Received"="下载数据量"
"Success upload files"="成功上传文件"
"File type not allowed"="文件类型不被支持"
"File size exceeds limit"="文件大小超过限制"