[mode]
name = project

[site]
debug = False

[database]
# engine，Accept (sqlite、mysql、oracle、postgresql)
engine = sqlite
name = db_name
user = db_user
password = db_pwd
host = db_host
port = db_port

[locale]
# language = 'zh-hans'
# timezone = 'Asia/Shanghai'

[image_upload]
suffix_name = jpg, jpeg, gif, png, bmp, webp

[throttle]
allocation_seconds = 1
throttle_seconds = 10