[tool.poetry]
name = "bomiot"
version = "1.3.0"
description = "No-environment delivery tool for Python apps Compile to binary · Cross-platform · Incremental updates · Source code protection"
authors = ["Bomiot <Singosgu@gmail.com>"]
readme = "README.md"
homepage = "https://www.bomiot.com"
repository = "https://github.com/Bomiot/Bomiot"
keywords = ["Bomiot", "bomiot", "GreaterWMS", "greaterwms"]
include = [
    "LICENSE"
]

exclude = [
]

classifiers = [
    'License :: OSI Approved :: MIT License',
    'Programming Language :: Python :: 3.9',
    'Programming Language :: Python :: 3.10',
    'Programming Language :: Python :: 3.11',
    'Programming Language :: Python :: 3.12',
    'Programming Language :: Python :: 3.13',
    'Programming Language :: Python :: Implementation :: CPython',
    'Programming Language :: Python :: Implementation :: PyPy'
]

[tool.poetry.dependencies]
python = ">=3.9,<=3.13"
django = "~4.2.24"
django-cors-headers = "~4.4.0"
pyjwt = ">=2.10.1"
django-filter = "~24.3"
djangorestframework-csv = "~3.0.2"
bomiot-asgi = ">=0.6.26"
bomiot-message = ">=0.4.6"
bomiot-token = ">=0.7.16"
orjson = "~3.10.7"
djangorestframework = "~3.15.2"
django-apscheduler = "~0.7.0"
pandas = "~2.2.3"
watchdog = "~6.0.0"
tomlkit = "~0.13.2"
openpyxl = "~3.1.5"
psutil = "~7.2.2"
xlsxwriter = "~3.2.3"
requests = "~2.32.3"
uvicorn = {extras = ["standard"], version = "~0.35.0"}
httptools = "~0.6.4"
aiofiles = "~24.1.0"
starlette = "~0.46.2"
a2wsgi = "~1.10.10"
fastapi = "~0.115.14"
flask = "~3.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
bomiot = "bomiot.cmd.cmd:cmd"