[uwsgi]
socket=127.0.0.1:8008
stats = 127.0.0.1:9000
master = true
processes = 5
threads = 5
chdir = /bomiot
wsgi-file= /bomiot/wsgi.py
memory-report = true
auto-procname = true
logto = /bomiot/log/uwsgi_log.log
chmod-socket = 660
vacuum = true
enable-threads = true
max-requests = 1000
reload-on-as = 1024
reload-on-rss = 100
evil-reload-on-as = 2048
evil-reload-on-rss = 2048
buffer-size = 65536
http-timeout = 300
socket-timeout = 300
reload-mercy = 1
worker-reload-mercy = 1