# Generated by Django 4.2.23 on 2025-08-31 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_pypi'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='project',
            field=models.CharField(default='bomiot', verbose_name='Project Name'),
        ),
        migrations.AddField(
            model_name='asn',
            name='project',
            field=models.CharField(default='bomiot', verbose_name='Project Name'),
        ),
        migrations.AddField(
            model_name='bar',
            name='project',
            field=models.CharField(default='bomiot', verbose_name='Project Name'),
        ),
        migrations.AddField(
            model_name='bin',
            name='project',
            field=models.CharField(default='bomiot', verbose_name='Project Name'),
        ),
        migrations.AddField(
            model_name='capital',
            name='project',
            field=models.CharField(default='bomiot', verbose_name='Project Name'),
        ),
        migrations.AddField(
            model_name='cpu',
            name='project',
            field=models.CharField(default='bomiot', verbose_name='Project Name'),
        ),
        migrations.AddField(
            model_name='customer',
            name='project',
            field=models.CharField(default='bomiot', verbose_name='Project Name'),
        ),
        migrations.AddField(
            model_name='department',
            name='project',
            field=models.CharField(default='bomiot', verbose_name='Project Name'),
        ),
        migrations.AddField(
            model_name='disk',
            name='project',
            field=models.CharField(default='bomiot', verbose_name='Project Name'),
        ),
        migrations.AddField(
            model_name='dn',
            name='project',
            field=models.CharField(default='bomiot', verbose_name='Project Name'),
        ),
        migrations.AddField(
            model_name='driver',
            name='project',
            field=models.CharField(default='bomiot', verbose_name='Project Name'),
        ),
        migrations.AddField(
            model_name='example',
            name='project',
            field=models.CharField(default='bomiot', verbose_name='Project Name'),
        ),
        migrations.AddField(
            model_name='fee',
            name='project',
            field=models.CharField(default='bomiot', verbose_name='Project Name'),
        ),
        migrations.AddField(
            model_name='files',
            name='project',
            field=models.CharField(default='bomiot', verbose_name='Project Name'),
        ),
        migrations.AddField(
            model_name='goods',
            name='project',
            field=models.CharField(default='bomiot', verbose_name='Project Name'),
        ),
        migrations.AddField(
            model_name='joblist',
            name='project',
            field=models.CharField(default='bomiot', verbose_name='Project Name'),
        ),
        migrations.AddField(
            model_name='memory',
            name='project',
            field=models.CharField(default='bomiot', verbose_name='Project Name'),
        ),
        migrations.AddField(
            model_name='message',
            name='project',
            field=models.CharField(default='bomiot', verbose_name='Project Name'),
        ),
        migrations.AddField(
            model_name='network',
            name='project',
            field=models.CharField(default='bomiot', verbose_name='Project Name'),
        ),
        migrations.AddField(
            model_name='permission',
            name='project',
            field=models.CharField(default='bomiot', verbose_name='Project Name'),
        ),
        migrations.AddField(
            model_name='pids',
            name='project',
            field=models.CharField(default='bomiot', verbose_name='Project Name'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='project',
            field=models.CharField(default='bomiot', verbose_name='Project Name'),
        ),
        migrations.AddField(
            model_name='stock',
            name='project',
            field=models.CharField(default='bomiot', verbose_name='Project Name'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='project',
            field=models.CharField(default='bomiot', verbose_name='Project Name'),
        ),
        migrations.AddField(
            model_name='team',
            name='project',
            field=models.CharField(default='bomiot', verbose_name='Project Name'),
        ),
        migrations.AddField(
            model_name='throttlemodel',
            name='project',
            field=models.CharField(default='bomiot', verbose_name='Project Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='project',
            field=models.CharField(default='bomiot', verbose_name='Project Name'),
        ),
    ]
