name: Auto-assign issues and pull requests

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-assign
        uses: pozil/auto-assign@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: |
            @Singosgu
          reviewers: |
            @Singosgu
          skipKeywords: |
            wip
            draft 