name: Database Backup

on:
  schedule:
    - cron: '0 2 * * *'  # Daily at 2 AM UTC
  workflow_dispatch:  # Manual trigger

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create backup
        run: |
          python manage.py dumpdata --exclude auth.permission --exclude contenttypes > backup_$(date +%Y%m%d_%H%M%S).json
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Upload backup to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: database-backup
          path: backup_*.json
          retention-days: 30

      - name: Upload to cloud storage
        if: github.event_name == 'schedule'
        run: |
          # Add your cloud storage upload logic here
          echo "Uploading backup to cloud storage..." 